export const projectDescriptions = [
	{
		id:0,
		name:'Pure Beauty E-Commerce Website',
		date: 'March 2023',
		image1: '/pureBeautyHome.jpg',
		description: 'This is an e-commerce website for a beauty shop belonging to a relative of a friend of mine.',
		team: 'For this project, my team included Kevin Ibanez, Ismael Ibanez and Ben Williams.',
		image2: '/pureBeautyServices.jpg',
		description2: 'I worked on the services page. This page shows all the services that are offered.',
		image3: '/pureBeautyShop.jpg',
		description3: 'I worked on the Shop page. This page will show all of the products that are sold in the shop.',
    link: 'https://kevinibanez.site',
	},
	{
		id:1,
		name:'Movie Reviews MVC',
		date: 'Fall 2020',
		image1: '/movieReviewsMVC.jpg',
		description: 'The goal of this project was to create a working MVC using SpringBoot and Thymeleaf in Java. The frontend is simple HTML with CSS.',
		team: 'For this project, my team included Tyler Gandy and Mulat Dagebo. We called our team the DreamCatchers.',
		image2: '/movieReviewsMVC2.jpg',
		description2: 'Each entry included information about the movie.',
		image3: '/movieReviewsMVC3.jpg',
		description3: 'The review site included a way for a user to add a review to the website through this form.',
		link:'',
	},
	{
		id:2,
		name:'Donut Maker App',
		date: 'Fall 2020',
		image1: '/donutMakerApp.jpg',
		description: 'The goal of this project was to create an App that mimicked the Cookie Clicker using JavaScript.',
		team: 'This was a solo project.',
		image2: '/donutMakerApp2.jpg',
		description2: 'When enough donuts are made, the options to purchase a multiplier and an autoclicker are available.',
		image3: '',
		description3: '',
		link:'',
	},
	{
		id:3,
		name:`Marvin's Metalheads Music`,
		date: 'Fall 2020',
		image1: '/marvinsMetalheadsMusicAPI.jpg',
		description: 'The goal of this project was to create an API that would display songs and albums being played.',
		team: 'For this project my team was: Pete Schaaf, Stella Law and David Alverado.',
		image2: '',
		description2: '',
		image3: '',
		description3: '',
		link:'',
	},
]