export const projectDescriptions = [
	{
		id:5,
		name:'LEOM Suppliers E-Commerce Website',
		date: 'March 2023',
		image1: '/LEOMHeadline.jpg',
		description: 'This is an e-commerce website for an apparel supplier for my husband.',
		team: 'TEAM: Kevin Ibanez',
		image2: '/LEOMProducts.jpg',
		description2: 'I worked on the products component. This component shows the products by category, selected using the buttons on the top.',
		image3: '/LEOMContact.jpg',
		description3: 'I worked on the Contact component. This component includes a form that sends the contact information to a company email.',
    link: '',
	},
	{
		id:0,
		name:'Pure Beauty E-Commerce Website',
		date: 'March 2023',
		image1: '/pureBeautyHome.jpg',
		description: 'This is an e-commerce website for a beauty shop belonging to a relative of a friend of mine.',
		team: 'TEAM: Kevin Ibanez, Ismael Ibanez and Ben Williams',
		image2: '/pureBeautyServices.jpg',
		description2: 'I worked on the services page. This page shows all the services that are offered.',
		image3: '/pureBeautyShop.jpg',
		description3: 'I worked on the Shop page. This page will show all of the products that are sold in the shop.',
    link: 'https://kevinibanez.site',
	},
	{
		id:1,
		name:'Movie Reviews MVC',
		date: 'Fall 2020',
		image1: '/movieReviewsMVC.jpg',
		description: 'The goal of this project was to create a working MVC using SpringBoot and Thymeleaf in Java. The frontend is simple HTML with CSS.',
		team: 'TEAM: Tyler Gandy and Mulat Dagebo. We called our team the DreamCatchers.',
		image2: '/movieReviewsMVC2.jpg',
		description2: 'Each entry included information about the movie.',
		image3: '/movieReviewsMVC3.jpg',
		description3: 'The review site included a way for a user to add a review to the website through this form.',
		link:'',
	},
	{
		id:2,
		name:'Donut Maker App',
		date: 'Fall 2020',
		image1: '/donutMakerApp.jpg',
		description: 'The goal of this project was to create an App that mimicked the Cookie Clicker using JavaScript.',
		team: 'TEAM: This was a solo project',
		image2: '/donutMakerApp2.jpg',
		description2: 'When enough donuts are made, the options to purchase a multiplier and an autoclicker are available.',
		image3: '',
		description3: '',
		link:'',
	},
	{
		id:3,
		name:`Marvin's Metalheads Music`,
		date: 'Fall 2020',
		image1: '/marvinsMetalheadsMusicAPI.jpg',
		description: 'The goal of this project was to create an API that would display songs and albums being played.',
		team: 'TEAM: Pete Schaaf, Stella Law and David Alverado.',
		image2: '',
		description2: '',
		image3: '',
		description3: '',
		link:'',
	},
	{
		id:4,
		name:'Taskr Final Project',
		date: 'Fall 2020',
		image1: '/TaskrAllUsers.jpg',
		description: 'The goal of this project was to create an application that would distribute household tasks to all household members.',
		team: 'TEAM: David Alverado, Joseph Gathuru, Jane Wetherholt, Ryan Archer, Munir Sefer, and Millicent Duke.',
		image2: '/TaskrAllTasks.jpg',
		description2: 'Joseph and I worked on creating the frontend for this project. This view shows all the tasks created for this sample household.',
		image3: '/TaskrMomView.jpg',
		description3: 'This page shows all the tasks assigned to a user (Mom) and her progress in completing them. On the lower half of the page, we have a calendar and a progress bar.',
		link:'',
	},
]